### ISSUE TITLE
Add functionality to admin pages

### ISSUE THREAD

**Issue by egolde1** [egolde1/VDIMS#9]
This includes the inventory table w/ view link for each vehicle update page, a remove vehicle button, and an add vehicle page, passing parameters is necessary here

**Comment by egolde1** [comment]
Add vehicle page will need a single file upload w validators for filetype and size, must rename image to imn. this simplifies routing to the image

**Comment by Khutor** [comment]
mostly done; only thing left doing is adding the ability to delete rows from inventory.aspx
